version: "3.7"
services:
  goobi-workflow:
    ## use prebuilt image with default plugins:
    image: intranda/goobi-workflow:default-plugins
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: goobi_metadata
        target: /opt/digiverso/goobi/metadata
      - type: volume
        source: goobi_exportfolder
        target: /opt/digiverso/viewer/hotfolder
      ## mount local directories with plugins and config:
      # - type: bind
      #   source: /local/path/to/my/goobi/plugins
      #   target: /opt/digiverso/goobi/plugins
      # - type: bind
      #   source: /local/path/to/my/goobi/config
      #   target: /opt/digiverso/goobi/config
    environment:
      - DB_SERVER=goobi-workflow-db
    depends_on: 
      - goobi-workflow-db
    restart: unless-stopped

  goobi-workflow-db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: goobi
      MYSQL_DATABASE: goobi
      MYSQL_USER: goobi
      MYSQL_PASSWORD: goobi
    volumes:
      - type: bind
        source: ./db/goobi_blank.sql
        target: /docker-entrypoint-initdb.d/goobi_blank.sql
      - type: volume
        source: goobi_dbdata
        target: /var/lib/mysqldata
    restart: unless-stopped


volumes:
  goobi_metadata:
  goobi_dbdata:
  goobi_exportfolder:
